package students.viktors_cesnokovs.lesson_12.level_3.task_21;

public class TestException {
    //Какой результат мы получим?

    //1. Got the Test Exception
    //   Inside finally block

}
