package students.nikita_bobrovs.lesson_12.level_3.task_21;

class TestException {
    //2. Got the Test Exception
    //
    //3. Inside finally block

    //Block finally executes in any case
}
