package students.jekaterina_aleksejeva.lesson_12.level_3.task_21;

public class task21reply {
    /* Мы получим:
    1. Got the Test Exception
       Inside finally block

     */
}
